name: CI

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10
      - run: echo "Hello"
